-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Person"
(
    "PersonID" character varying(255) NOT NULL,
    "Birth" numeric,
    "SexName" character varying(255),
    "RegionID" integer,
    "RegTypeName" character varying(255),
    "ClassProfileName" character varying(255),
    "EOName" character varying(255),
    PRIMARY KEY ("PersonID")
);

CREATE TABLE public."Region"
(
    "RegionID" serial NOT NULL,
    "RegName" character varying(255),
    "AreaName" character varying(255),
    "TerName" character varying(255),
    "TerTypeName" character varying(255),
    PRIMARY KEY ("RegionID")
);

CREATE TABLE public."EO"
(
    "EOName" character varying(255) NOT NULL,
    "EOTypeName" character varying(255),
    "EOParent" character varying(255),
    "RegionID" integer,
    "ClassLang" character varying(255),
    PRIMARY KEY ("EOName")
);

CREATE TABLE public."Test"
(
    "PersonID" character varying(255) NOT NULL,
    "TestName" character varying(255) NOT NULL,
    "Year" numeric NOT NULL,
    "TestStatus" character varying(255),
    "Ball100" numeric,
    "Ball12" numeric,
    "Ball" numeric,
    "AdaptScale" numeric,
    "PTEOName" character varying(255),
    "Lang" character varying(255),
    PRIMARY KEY ("Year", "PersonID", "TestName")
);

ALTER TABLE public."Person"
    ADD FOREIGN KEY ("RegionID")
    REFERENCES public."Region" ("RegionID")
    NOT VALID;


ALTER TABLE public."Person"
    ADD FOREIGN KEY ("EOName")
    REFERENCES public."EO" ("EOName")
    NOT VALID;


ALTER TABLE public."Test"
    ADD FOREIGN KEY ("PersonID")
    REFERENCES public."Person" ("PersonID")
    NOT VALID;


ALTER TABLE public."EO"
    ADD FOREIGN KEY ("RegionID")
    REFERENCES public."Region" ("RegionID")
    NOT VALID;


ALTER TABLE public."Test"
    ADD FOREIGN KEY ("PTEOName")
    REFERENCES public."EO" ("EOName")
    NOT VALID;

END;